const suggestions = [
    { id: 1, description: 'A 501 - ACUARIOS DEL MAR S.A.' },
    { id: 2, description: 'B 220 - B 221 - B 222 - ACUICULTEC S.A. DE C.V.' },
    { id: 3, description: 'A 207 - A 208 - ADITIVOS Y ALIMENTOS S.A. ADILISA' },
    { id: 4, description: 'A 408 - ADITMAQ ADITIVOS Y MAQUINARIAS CIA. LTDA.' },
    { id: 5, description: 'A 502 - AGEARTH ECUADOR' },
    { id: 6, description: 'A 100 - A 112 - AGRANTECH DEL ECUADOR AGRANTECUA S.A.' },
    { id: 7, description: 'A 511 - AGRIPAC S.A.' },
    { id: 8, description: 'A 311 - AQUASPOT' },
    { id: 9, description: 'A 608 - AGROBIMSA S.A.' },
    { id: 10, description: 'C 310 - AGROIMPORTADORA PLASTISEED S.A.' },
    { id: 11, description: 'C 205 - AGRORUM S.A.' },
    { id: 12, description: 'A 217 - A218 - A303 - AGROSUNCORP S.A.' },
    { id: 13, description: 'E 103 - AINSA S.A.' },
    { id: 14, description: 'B 214 - AIREC SAS' },
    { id: 15, description: 'A 607 - ALLTECH ECUADOR' },
    { id: 16, description: 'B 216 - AMPSOLUTECH SAS' },
    { id: 17, description: 'C 200 - AMUCO INC.' },
    { id: 18, description: 'A 507 - APOLO LEX APOLEXSA S.A.' },
    { id: 19, description: 'A 209 - A 123 - APPLIED BLUE BIOTECHNOLOGY APB-BIO C.A.' },
    { id: 20, description: 'A 403 - A 316 - A 307 - A 223 - A 308 - APRACOM S.A.' },
    { id: 21, description: 'B 115 - CARGILL' },
    { id: 22, description: 'P2 - AQUAFEED' },
    { id: 23, description: 'A 503 - AQUAGEN S.A.' },
    { id: 24, description: 'A 606 - AQUAGROW DEL ECUADOR AQUAGROWEC C.LTDA.' },
    { id: 25, description: 'A 404 - AQUAMARKET S.A.' },
    { id: 26, description: 'A 406 - AQUAPRIME S.A.' },
    { id: 27, description: 'C 311 - C 312 - AQUASALT S.A.' },
    { id: 28, description: 'A 714 - A 715 - AQUAYSISTEMAS S.A.' },
    { id: 29, description: 'B 223 - ARKEAS LAB S.A.' },
    { id: 30, description: 'A 800 - A 801 - BANCO PICHINCHA C.A.' },
    { id: 31, description: 'B 202 - BASC CAPÍTULO GUAYAQUIL' },
    { id: 32, description: 'C 313 - C 314 - BIGFISH S.A.' },
    { id: 33, description: 'A 708 - A 709 - BIOBAC S.A.' },
    { id: 34, description: 'A 610 - BIOFEEDER S.A.S.' },
    { id: 35, description: 'A 509 - BIOLAN ECUADOR MICROBIOSENSORES C. LTDA.' },
    { id: 36, description: 'A 614 - CALIZAS HUAYCO S.A.' },
    { id: 37, description: 'A 514 - A 515 - CARTONES NACIONALES S.A.I. CARTOPEL' },
    { id: 38, description: 'C 317 - C 318 - CARTORAMA C.A.' },
    { id: 39, description: 'A 809 - CENTRO DE MANTENIMIENTO ELÉCTRICO ELECTRICLASER S.A.' },
    { id: 40, description: 'A 204 - CHEMICAL PHARM DEL ECUADOR' },
    { id: 41, description: 'A 706 - A 713 - A 712 - CODEMET S.A.' },
    { id: 42, description: 'A 612 - CODIELECTRIC S.A.' },
    { id: 43, description: 'A 703 - COFIMAR' },
    { id: 44, description: 'A 516 - A 604 - CONSORCIO INTERANDINO, INTERCONSORCIO S.A.' },
    { id: 45, description: 'C 309 - CONSTRUCCIONES HIPACA S.A.' },
    { id: 46, description: 'A 111 - CONTROL UNION PERU S.A.C.' },
    { id: 47, description: 'C 319 - C 210 - COREPTEC S.A.' },
    { id: 48, description: 'C 308 - CORPORACIÓN DE REPRESENTACIÓN Y SERVICIOS TECNICO COREPTEC S.A.' },
    { id: 49, description: 'B 105 - B 106 - B 107 - CRETAR S.A.' },
    { id: 50, description: 'A 401 - DAPETSA S.A.' },
    { id: 51, description: 'B 122 - DATANALITIC SAS' },
    { id: 52, description: 'A 219 - A 220 - DELTA DELFINI & CIA., S.A.' },
    { id: 53, description: 'A 203 - DIMUNE S.A.' },
    { id: 54, description: 'A 104 - DISAN ECUADOR S.A.' },
    { id: 55, description: 'A 213 - DISTRIBUIDORA M Y F MERCHAN Y FONTANA CIA. LTDA.' },
    { id: 56, description: 'C 320 - DIVERSQUIM S.A. DWE' },
    { id: 57, description: 'A 313 - ECOTECHNOLOGY SOLUTIONS S.A.' },
    { id: 58, description: 'C 111 - ECUAMEX INDUSTRIA - ACUICOLA S.A.' },
    { id: 59, description: 'B 119 - B 120 - ELANCO CHILE SPA' },
    { id: 60, description: 'A 705 - EMBIOTEC ECUADOR S.A. EMBIOECSA' },
    { id: 61, description: 'B 226 - EMERGENT COLD ECUADOR S.A.S.' },
    { id: 62, description: 'A 304 - A 305 - EMPACRECI S.A.' },
    { id: 63, description: 'B 100 - B 101 - B 102 - B 103 - B 104 - ENERGYPLAM CIA. LTDA.' },
    { id: 64, description: 'B 109 - B 110 - B 111 - ADM' },
    { id: 65, description: 'A 505 - EQUIPOS Y TRANSPORTES S.A.' },
    { id: 66, description: 'A 200 - A 201 - BINATEK' },
    { id: 67, description: 'C 315 - ETEC INTERNATIONAL INC.' },
    { id: 68, description: 'B 218 - EVONIK ECUADOR S.A.' },
    { id: 69, description: 'A 301 - A 302 - EXPALSA EXPORTADORA DE ALIMENTOS S.A.' },
    { id: 70, description: 'A 317 - EXPORTADORA TOTAL SEAFOOD TOTALSEAFOOD S.A.' },
    { id: 71, description: 'A 411 - A 410 - EXPORTQUILSA & PRODUCTORES ASOCIADOS S.A.' },
    { id: 72, description: 'A 214 - EXPOTUNA S.A.' },
    { id: 73, description: 'B 215 - EXTRU - TECH' },
    { id: 74, description: 'B 121 - FARMAGRO S.A.' },
    { id: 75, description: 'A 504 - A 412 - FARMAVET FARMACOS VETERINARIOS S.A.' },
    { id: 76, description: 'C 104 - FEHIERRO' },
    { id: 77, description: 'B 213 - FIDEICOMISO DE ADMINISTRACIÓN COMANDATO VIC' },
    { id: 78, description: 'B 224 - FILTRATEK S.A.S.' },
    { id: 79, description: 'A 711 - FISECORP S.A.' },
    { id: 80, description: 'A 310 - FRAMACUA S.A.' },
    { id: 81, description: 'A 309 - FRIGOLANDIA S.A.' },
    { id: 82, description: 'B 201 - FURZZA S.A.' },
    { id: 83, description: 'A 508 - GENICS PTY LTD' },
    { id: 84, description: 'A 312 - SKRETTING' },
    { id: 85, description: 'A 314 - A 315 - SKRETTING' },
    { id: 86, description: 'C 208 - GLOBAL ECUADOR' },
    { id: 87, description: 'A 215 - A 216 - GRAFIMPAC S.A.' },
    { id: 88, description: 'A 704 - GREAT SALT LAKE ARTEMIA' },
    { id: 89, description: 'B 225 - GREEN PLAINS INC.' },
    { id: 90, description: 'A 202 - A 115 - GRUPASA' },
    { id: 91, description: 'A 108 - GRUPO CORPORATIVO SERVINCO (GABELLI S.A)' },
    { id: 92, description: 'B 209 - B 125 - HAID (ECUADOR) FEED CIA. LTDA.' },
    { id: 93, description: 'B 219 - HANNA INSTRUMENTS ECUADOR S.A. HANNAINST' },
    { id: 94, description: 'E 101 - HESTIA - G S.A.' },
    { id: 95, description: 'A 402 - TOTEM' },
    { id: 96, description: 'A 120 - A 121 - IASA S.A.' },
    { id: 97, description: 'E 104 - IASA S.A.' },
    { id: 98, description: 'C 110 - ILGUECORP S.A.' },
    { id: 99, description: 'A 306 - IMETECO S.A.' },
    { id: 100, description: 'B 200 - INDUSTRIA AGROPECUARIA INDAMI CIA. LTDA.' },
    { id: 101, description: 'A 206 - INDUSTRIA CARTONERA ECUATORIANA S.A.' },
    { id: 102, description: 'A 512 - INDUSTRIA CARTONERA PALMAR INCARPALM S.A.' },
    { id: 103, description: 'B 228 - INDUSTRIA PESQUERA SANTA PRISCILA S.A.' },
    { id: 104, description: 'C 321 - INDUSTRIA QUÍMICA INVESTCAMP S.A.' },
    { id: 105, description: 'A 405 - INDUSTRIAL ACUICOLA OCHOA & BARCIA DINACUAMAR CIA. LTDA.' },
    { id: 106, description: 'A 804 - INDUSTRIAS DE MINERALES LA COLINA INDUCOLINA CIA. LTDA.' },
    { id: 107, description: 'C 204 - INDUSUR INDUSTRIAL DEL SUR S.A.' },
    { id: 108, description: 'E 106 - E 107 - INDUSUR INDUSTRIAL DEL SUR S.A.' },
    { id: 109, description: 'B 212 - INGEMSA SA INGENIERIA ELECTROMECANICA' },
    { id: 110, description: 'A 222 - A 221 - INPROEL S.A.' },
    { id: 111, description: 'A 613 - INPROSA INDUSTRIAL PROCESADORA SANTAY S.A.' },
    { id: 112, description: 'C 304 - INRIOCH S.A.' },
    { id: 113, description: 'A 702 - A 609 - INSTALACIONES ELECTROMECANICAS S.A. INESA' },
    { id: 114, description: 'A 811 - INTELARTE S.A.' },
    { id: 115, description: 'A 107 - INVECUADOR S.A.' },
    { id: 116, description: 'A 700 - IOSA ECUADOR IOSECU S.A.' },
    { id: 117, description: 'A 300 - KARASTE S.A.' },
    { id: 118, description: 'A 810 - KSE PROCESS TECHNOLOGY B.V.' },
    { id: 119, description: 'C 209 - LABOMERSA S.A.' },
    { id: 120, description: 'B 217 - LAITRAM MACHINERY LLC' },
    { id: 121, description: 'B 227 - LAVILISTA' },
    { id: 122, description: 'A 710 - LINEXPRES S.A.' },
    { id: 123, description: 'A 803 - MAGIC VALLEY HELI -ARC, MFG., INC.' },
    { id: 124, description: 'E 102 - MAGROCAM // SONI RIQUELME FREIRE OCHOA' },
    { id: 125, description: 'A 802 - MAPRIPLASTEC S.A.' },
    { id: 126, description: 'C 201 - MAREAUTO S.A.' },
    { id: 127, description: 'A 205 - MARINE INSTRUMENTS' },
    { id: 128, description: 'C 108 - MARMOI S.A.' },
    { id: 129, description: 'B 112 - B 113 - B 114 - MAYEKAWA ECUADOR S.A.' },
    { id: 130, description: 'C 300 - MEGASUPPLY ECUADOR S.A.' },
    { id: 131, description: 'B 208 - METROINVESTSA S.A.' },
    { id: 132, description: 'C 106 - MINNOWTECH' },
    { id: 133, description: 'A 510 - MOLINOS CHAMPION S.A.S.' },
    { id: 134, description: 'A 506 - NATURAL STAR S.A. NASSTAR' },
    { id: 135, description: 'C 109 - NAVECUADOR S.A.' },
    { id: 136, description: 'A 105 - A 106 - NEGOCIOS INDUSTRIALES REAL NIRSA S.A.' },
    { id: 137, description: 'A 413 - A 414 - NEPROPAC S.A.' },
    { id: 138, description: 'C 303 - NEUMATICOS Y CADENAS NEUMAC S.A.' },
    { id: 139, description: 'A 400 - NL PROINSU S.A.' },
    { id: 140, description: 'C 307 - ' },
    { id: 141, description: 'A 601 - A 602 - OMARSA S.A.' },
    { id: 142, description: 'C 202 - ONLY CONTROL S.A. CONONLY' },
    { id: 143, description: 'P1 - PANORAMA ACUÍCOLA' },
    { id: 144, description: 'B 123 - B 124 - PAPELERA NACIONAL S.A.' },
    { id: 145, description: 'E 105 - PESCAEQUIPOS S.A.' },
    { id: 146, description: 'A 114 - PICA PLASTICOS INDUSTRIALES' },
    { id: 147, description: 'C 100 - C 101 - PLASTICOS RIVAL CIA. LTDA.' },
    { id: 148, description: 'B 116 - PLASTIMET INDUSTRIAS METAL PLÁSTICAS S.A.' },
    { id: 149, description: 'B 203 - B 204 - POET BIOPRODUCTS' },
    { id: 150, description: 'A 500 - POLIGRUP S.A.' },
    { id: 151, description: 'A 600 - PQA PRODUCTORES QUIMICOS ECUATORIANOS S.A.' },
    { id: 152, description: 'A 611 - PRILABSA' },
    { id: 153, description: 'A 409 - PROBAC S.A.' },
    { id: 154, description: 'C 203 - PROBRISA S.A.' },
    { id: 155, description: 'C 107 - PRODUCTORA CARTONERA S.A.' },
    { id: 156, description: 'B 117 - B 118 - PROQUALIA S.A.' },
    { id: 157, description: 'A 118 - QUIMISER S.A.' },
    { id: 158, description: 'A 103 - REDBARNGROUP ECUADOR C.L.' },
    { id: 159, description: 'C 301 - RIMFROST AS.' },
    { id: 160, description: 'B 210 - B 211 - ROTOGAL SLU' },
    { id: 161, description: 'A 119 - S.G.S DEL ECUADOR S.A.' },
    { id: 162, description: 'A 605 - SACOS DURAN REYSAC' },
    { id: 163, description: 'B 205 - B 206 - SAEPLAST AMERICAS INC.' },
    { id: 164, description: 'E 100 - SALCEDO MOTORS' },
    { id: 165, description: 'A 101 - A 102 - SALCEDO MOTORS' },
    { id: 166, description: 'A 116 - SEATEC S.A.' },
    { id: 167, description: 'C 302 - SEDEMI SERVICIOS DE MECÁNICA INDUSTRIAL DISEÑO CONSTRUCCIÓN Y MONTAJE S.C.C.' },
    { id: 168, description: 'A 407 - SOCIEDAD NACIONAL DE GALÁPAGOS C.A.' },
    { id: 169, description: 'B 207 - SOLAR TEAM SAS' },
    { id: 170, description: 'B 108 - SOLUCIONES PLÁSTICAS INDUSTRIALES S.A. SOLIPLAST S.A.' },
    { id: 171, description: 'A 805 - A 806 - SOLUINMAQ SOLUCIONES, INSUMOS Y MAQUINARIAS' },
    { id: 172, description: 'A2 - SUBSECRETARÍA DE CALIDAD E INOCUIDAD' },
    { id: 173, description: 'A 807 - SUMELEC S.A.' },
    { id: 174, description: 'C 206 - C 207 - C 305 - C 306 - SVF ECUADOR S.A.' },
    { id: 175, description: 'A 117 - TAIZHOU QIHONG ELECTRICAL MECHANICAL CO. LTD.' },
    { id: 176, description: 'A 122 - TELEARSEG S.A.S.' },
    { id: 177, description: 'A 603 - TELEMETRIA AQUICOLA (AQUAMETRICS) S.A.' },
    { id: 178, description: 'C 105 - THE CENTER FOR AQUACULTURE TECHNOLOGIES' },
    { id: 179, description: 'A 808 - TOP TRADING TOPTRA CIA. LTDA.' },
    { id: 180, description: 'A 210 - TRANSPORTE Y LOGISTICA TORRES S.A. LOGISTORRES' },
    { id: 181, description: 'A 513 - TRESVICOR S.A.' },
    { id: 182, description: 'A 707 - UNITED STATES SOYBEAN EXPORT COUNCIL USSEC' },
    { id: 183, description: 'A 701 - VENTAS AVICOLAS VETAVES CIA. LTDA.' },
    { id: 184, description: 'C 316 - VEPAMIL S.A.' },
    { id: 185, description: 'A 212 - VITAPRO ECUADOR CIA. LTDA.' },
    { id: 186, description: 'A 124 - VITAPRO ECUADOR CIA. LTDA.' },
    { id: 187, description: 'C 103 - WENGER MANUFACTURING' },
    { id: 188, description: 'A 109 - A 110 - XPERTSEA S.A.' },
    { id: 189, description: 'C 102 - ZC MAYORISTAS S.A.' },
    { id: 190, description: 'A 113 - ZEIGLER BROS INC.' },
];
